spring:
  datasource:
    url: jdbc:mysql://115.159.71.166:3306/Intelligent_office
    username: root
    password: root
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#  http:
#    multipart:
#      max-file-size: 20Mb
#      max-request-size: 20Mb
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
app:
  config:
    server: http://localhost:8082
    front: http://localhost:8081/#/
server:
  port: 8082