spring:
  datasource:
    url: jdbc:mysql://115.159.71.166:3306/Intelligent_office
    username: root
    password: root
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
http:
  multipart:
    max-file-size: 20Mb
    max-request-size: 20Mb
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
#app:
#  config:
#    server: http://localhost:8082
#    front: http://localhost:8081/#/
server:
  port: 8086
#Configuration:
#  status: warn

Properties: # 定义变量
   Property:
    - name: log.path
      value: d:\\tmp\\logs
    - name: project.name
      value: spring-boot-log

#Appenders:
#  Console:  #输出到控制台
#    name: CONSOLE
#    target: SYSTEM_OUT
#    ThresholdFilter:
#      level: trace
#      onMatch: ACCEPT
#      onMismatch: DENY
#    PatternLayout:
#      pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
#
#  # 输出到文件，超过128MB归档
#  RollingFile:
#    - name: ROLLING_FILE
#      ignoreExceptions: false
#      fileName: ${log.path}/${project.name}.log
#      filePattern: "${log.path}/$${date:yyyy-MM}/${project.name}-%d{yyyy-MM-dd}-%i.log.gz"
#      PatternLayout:
#        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
#      Policies:
#        SizeBasedTriggeringPolicy:
#          size: "128 MB"
#      DefaultRolloverStrategy:
#        max: 1000

Loggers:
  Root:
    level: info
    AppenderRef:
      - ref: CONSOLE
      - ref: ROLLING_FILE
  Logger: # 为com.xjj包配置特殊的Log级别，方便调试
    - name: com.test.dao
      additivity: false
      level: debug
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE